---
version: '3'

services:

  # AWS RDS, Engine version 10.6
  gear-engine-test-postgres:
    image: postgres:10.6
#    platform: linux/amd64
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=pass
    - POSTGRES_DB=gear-engine-test
    volumes:
    - gear-engine-test-pgdata:/var/lib/postgresql/data/

  # AWS ElastiCache, Engine version 5.0.3
  gear-engine-test-redis:
    image: redis:5.0.3
#    platform: linux/amd64
    ports:
    - 6379:6379

  # RUBYOPT='-W0' bundle exec rake spec
  gear-engine-test:
    platform: linux/amd64
    build: test
    volumes:
    - ../:/gear-engine/
    - gear-engine-bundle:/usr/local/bundle/
#    command: /gear-engine/devbox/test/guard
    stdin_open: true
    tty: true

volumes:

  gear-engine-bundle:
  gear-engine-test-pgdata: