version: '3'

services:

  gear-engine-specs:
    build: specs
    volumes:
    - ../:/gear-engine
    - gear-engine-specs-bundle:/usr/local/bundle
    command: /gear-engine/devbox/specs/guard
    stdin_open: true
    tty: true

volumes:

  gear-engine-specs-bundle: